import { readFile, writeFile } from 'node:fs/promises';
import { initialCsharpCourse } from '../src/data/csharpCourse.ts';
import { GIT_LEVELS } from '../src/data/gitLevelsData.ts';

const q = value => value == null ? 'null' : "'" + String(value).replaceAll("'", "''") + "'";
const json = value => q(JSON.stringify(value)) + '::jsonb';
const rows = [];
function upsert(table, data) {
  const keys = Object.keys(data);
  rows.push(`insert into public.${table} (${keys.join(',')}) values (${Object.values(data).join(',')}) on conflict (${table === 'task_checks' ? 'task_id' : 'id'}) do update set ${keys.slice(1).map(k => `${k}=excluded.${k}`).join(',')};`);
}
for (const course of [initialCsharpCourse, { id: 'git-branching', title: 'Git Branching Lab', language: 'Git', description: 'Практика Git', version: '1', modules: [] }]) {
  upsert('courses', Object.fromEntries(['id','title','language','description','version'].map(k => [k,q(course[k])])));
}
for (const mod of initialCsharpCourse.modules) {
  upsert('modules', { id:q(mod.id),course_id:q(mod.courseId),title:q(mod.title),description:q(mod.description),order_index:mod.orderIndex,icon_name:q(mod.iconName) });
  for (const lesson of mod.lessons) {
    upsert('lessons',{id:q(lesson.id),module_id:q(mod.id),title:q(lesson.title),slug:q(lesson.slug),order_index:lesson.orderIndex,description:q(lesson.description),estimated_minutes:lesson.estimatedMinutes});
    for (const [index,task] of lesson.tasks.entries()) {
      upsert('tasks',{id:q(task.id),lesson_id:q(lesson.id),title:q(task.title),type:q(task.type),difficulty:q(task.difficulty),xp:task.xp,instructions:q(task.instructions),theory_snippet:q(task.theorySnippet),initial_code:q(task.initialCode),solution_code:'null',tests:json([]),quiz_options:json((task.quizOptions||[]).map(({id,text})=>({id,text}))),hints:json(task.hints),order_index:index+1});
      upsert('task_checks',{task_id:q(task.id),tests:json(task.tests||[]),quiz_options:json(task.quizOptions||[]),solution_code:q(task.solutionCode)});
    }
  }
}
upsert('modules',{id:q('git-module'),course_id:q('git-branching'),title:q('Git Branching Lab'),order_index:1});
upsert('lessons',{id:q('git-lessons'),module_id:q('git-module'),title:q('Git практика'),slug:q('git-lab'),order_index:1});
for (const level of GIT_LEVELS) upsert('tasks',{id:q(level.id),lesson_id:q('git-lessons'),title:q(level.title),type:q('git'),difficulty:q(level.difficulty),xp:level.xp,instructions:q(level.description),order_index:level.number});
rows.push("insert into public.group_modules(group_name,module_id,course_id) select group_name,'git-module','git-branching' from public.group_courses where course_id='git-branching' on conflict(group_name,module_id) do nothing;");
const seed = '-- Generated by npm run seed:generate. All built-in C# and Git tasks.\nbegin;\n'+rows.join('\n')+'\ncommit;\n';
await writeFile('supabase/migrations/202609300002_curriculum.sql', seed);
const base = await readFile('supabase/base.sql','utf8');
const secure = await readFile('supabase/migrations/202609300001_secure_classroom.sql','utf8');
await writeFile('src/data/supabaseFullSetup.sql', '-- Generated: fresh install or upgrade.\n'+base+'\n'+secure+'\n'+seed);
// Legacy entry points must never reintroduce old permissive policies.
await writeFile('src/data/supabaseSchema.sql','-- Schema-only setup. Follow with curriculum migration.\n'+base+'\n'+secure);
await writeFile('src/data/fixApprovalAndRealtime.sql',secure);
